"""add is_verified_purchase to reviews

Revision ID: 93e04646eecd
Revises: c3a7f2e91d04
Create Date: 2026-09-01 11:31:30.478274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93e04646eecd'
down_revision: Union[str, Sequence[str], None] = 'c3a7f2e91d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_verified_purchase', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_verified_purchase')
    # ### end Alembic commands ###
