"""add shiprocket shipping fields to orders

Revision ID: d93077abdc18
Revises: b4e8c2a91d73
Create Date: 2026-09-25 14:46:05.587114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd93077abdc18'
down_revision: Union[str, Sequence[str], None] = 'b4e8c2a91d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shiprocket_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('shiprocket_shipment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('awb_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('courier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_label_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('manifest_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('shipment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('pickup_scheduled_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('tracking_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_orders_awb_code'), 'orders', ['awb_code'], unique=False)
    op.create_index(op.f('ix_orders_shiprocket_order_id'), 'orders', ['shiprocket_order_id'], unique=False)
    op.create_index(op.f('ix_orders_shiprocket_shipment_id'), 'orders', ['shiprocket_shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_shiprocket_shipment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_shiprocket_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_awb_code'), table_name='orders')
    op.drop_column('orders', 'tracking_data')
    op.drop_column('orders', 'pickup_scheduled_date')
    op.drop_column('orders', 'shipment_status')
    op.drop_column('orders', 'manifest_url')
    op.drop_column('orders', 'shipping_label_url')
    op.drop_column('orders', 'courier_id')
    op.drop_column('orders', 'courier_name')
    op.drop_column('orders', 'awb_code')
    op.drop_column('orders', 'shiprocket_shipment_id')
    op.drop_column('orders', 'shiprocket_order_id')
    # ### end Alembic commands ###
